### ISSUE TITLE
Allow Customization of Time/Date Display

### ISSUE THREAD

**Issue by ryanwalder** [prusa3d/Prusa-Link#1003]
PrusaLink on MK4(s)

I would like to be able to modify the way PrusaLink displays Time/Date information:

Current View, uses US data format (arguably the worst!):

![image](https://github.com/user-attachments/assets/d9722f77-ea1d-4806-9e7a-a0c8a529c87e)

I would like to be able to format this however I like (ideally with the same arguments as the linux `date` command, eg: `%Y-%m-%d %H:%M:%S`).

**Comment by 3d-gussner** [comment]
@ryanwalder This is the PrusaLink repository for the MK2.5/S and MK3/S/+ with a SBC or Linux computer. Please close the issue here and open it in the correct repository https://github.com/prusa3d/Prusa-Firmware-Buddy

**Comment by ryanwalder** [comment]
My bad! Thanks for the heads up.

**Comment by 3d-gussner** [comment]
@ryanwalder NP isn't easy to find the correct repository
