### ISSUE TITLE
Dependancy on the pi user

### ISSUE THREAD

**Issue by WilliamHJKL** [prusa3d/Prusa-Link#531]
It could be usefull to indicate that the pi user must exist to start Prusalink. If the pi user is replaced by another one, (during the personnalisation with rpi-imager by example) the daemon will not start.

**Comment by TojikCZ** [comment]
I know, I need to tell them louder, thanks for reminding me
![image](https://user-images.githubusercontent.com/5272796/194304201-0dada44f-b498-41ca-a1fa-c8ae21c9ae29.png)

**Comment by TojikCZ** [comment]
This should not be a problem in the RC2 image anymore
