### ISSUE TITLE
Bed temperature not consistently on trace

### ISSUE THREAD

**Issue by darraghbr** [prusa3d/Prusa-Link#535]
Since updating to 0.7.0.rc1 I have noticed that the bed temperature trace sometimes disappears

![image](https://user-images.githubusercontent.com/31858409/194300879-83a2ccbb-cfbd-4d02-b4f4-ad747192c95f.png)

For reference I am running on a Pi Zero 2 W and this has been happening for a number of days through a number of restarts.

**Comment by TojikCZ** [comment]
Hi, This is not a PrusaLink bug, the Connect side should be fixed and released Soon™ now in testing

**Comment by darraghbr** [comment]
> Hi, This is not a PrusaLink bug, the Connect side should be fixed and released Soon™ now in testing

Ok thanks, is it worth transferring this to another repo or just closing it?

**Comment by ondratu** [comment]
That repo is closed. Creating issues here is ok ;) Thanks!

**Comment by ondratu** [comment]
This should be fixed.
