### ISSUE TITLE
`Extruder fan` becomes `Hotend fan`

### ISSUE THREAD

**Issue by 3d-gussner** [prusa3d/Prusa-Link#540]
With MK2.5/S,MK3/S/+ firmware FW 3.12.0 and newer the `Extruder fan` will be replaced with `Hotend fan`.
To ensure consistent terms used across all printers, firmwares, documentation, etc.

Please update PrusaLink to support both or depending on the version the correct term.

Change https://github.com/prusa3d/Prusa-Link/blob/master/prusa/link/printer_adapter/state_manager.py#L442 ???
https://github.com/prusa3d/Prusa-Link/search?q=extruder
https://github.com/prusa3d/Prusa-Link/search?q=fan_extruder

See https://github.com/prusa3d/Prusa-Firmware/pull/3694

**Comment by TojikCZ** [comment]
Attempt to fix in #542

**Comment by 3d-gussner** [comment]
Please feel free to close it as soon the PR has been merged
