### ISSUE TITLE
add tasmota plugin 

### ISSUE THREAD

**Issue by yasars** [prusa3d/Prusa-Link#563]
hi can we add tasmota plugin ? my prusa has an relais for on/off the printer with tasmota.... i come from octoprint , i miss the feature ....but prusalink is really good, gives a lot of information about the printer! top now only the slicer is missing :D no matter if online or offline :D:D

**Comment by TojikCZ** [comment]
Hi, At first glance, Tasmota looks like a standalone thing you can add to your Pi. Feel free to log in through SSH and install Tasmota. Sorry, but we do not plan to integrate with smart switches and receptacles at this time. If there's anything I've misunderstood, feel free to correct me

**Comment by TojikCZ** [comment]
Yes, this will probably end up as one of the main gripes with PrusaLink, there won't be plugins. The MINI runs PrusaLink on its little tiny microcontroller, so while I could probably make that happen, the newer buddy based printers like the MINI would be left out, which isn't a good look. I hope the community will figure something out, but I'm afraid I can't help.

**Comment by yasars** [comment]
I just found a solution by adding prusalink to my home assistant, but somehow he wants the PrusaLink v2 api key :( so I guess it's just a matter of waiting, I can finally start the tasmota socket (relay) with my home assistant .... but everything is still in its infancy! I hope the online slicer will come "soon"
