### ISSUE TITLE
Bad X-Api-Key error when trying to upload from PrusaSlicer

### ISSUE THREAD

**Issue by darraghbr** [prusa3d/Prusa-Link#608]
I just updated to RC2, was working fine with RC1. 

I thought 'I wonder if the API key has changed' so I tried to upload from PrusaSlicer and got this error message.

![image](https://user-images.githubusercontent.com/31858409/210118509-4334b33a-c7f0-491a-ab95-71c2da0d523f.png)

After checking in the connect.prusa3d.com/printer/blah-blah-blah/settings  page I saw the API key had changed, so copy and paste into PrusaSlicer, hit test and I got the same error message.

I then went into the local UI just in case (prusalink.local/#settings) and in there was another API key, but a different one this time. Again copy paste into PrusaSlicer, same error message. 

I've double checked the IP in PrusaSlicer and that has not changed, tried the hostname instead, same issues. 

This issue is a real killer for me as I used it as part of my normal workflow so any help would be appreciated!

**Comment by Sarlochin** [comment]
Change the "Authorization Type" in prusa slicer from "API key" to "HTTP digest" to keep up your workflow

**Comment by TojikCZ** [comment]
You can still generate an API key under PrusaLink -> Settings -> API Key -> Reset
But we'd suggest sticking to the digest authentication. It is real shame, no-one is developing these standard login pop-ups anymore, expecting everyone to javascript together their own thing. These digest ones are still MD5 which is considered not secure. But no new algorhithms are supported by all major browsers.

**Comment by darraghbr** [comment]
I've tried it again today using the API key in PrusaLink and it all seems to be working now, so I will close this. 

I don't understand, this may well just be my issue.
