### ISSUE TITLE
Upgrade prusa link

### ISSUE THREAD

**Issue by khenderick** [prusa3d/Prusa-Link#611]
I would like to be able to upgrade Prusa-Link from within the web interface. I'm running 0.7.0 rc1 at this moment, and want to upgrade to 0.7.0 rc2, and would have loved to have a big "upgrade now" button available.

Awaiting such feature, what's currently the easiest way to upgrade? Re-flash the image?

**Comment by TojikCZ** [comment]
Yup, the current way to upgrade is to re-flash your image. We are adding some dependencies and changing the autostart script a bit, so the update cannot be done through pip alone

**Comment by TojikCZ** [comment]
The updater is now there, we'll see if it works shortly. Issue for that is here: #758 Closing this one
