### ISSUE TITLE
Display material, print time, weight and length of filament

### ISSUE THREAD

**Issue by Eldenroot** [prusa3d/Prusa-Link#612]
![image](https://user-images.githubusercontent.com/778890/210397150-b605b3b5-7798-4273-b6a2-6689db711f2b.png)

We can see these info on display, why not in PrusaLink?!

**Comment by TojikCZ** [comment]
Hi, this is not an issue with PrusaLink for the MK3, IDK where else to put it tho, so I'll leave this open for now and ask around.

**Comment by TojikCZ** [comment]
closing this as this repo is not tracked by anyone developing for the MINI

**Comment by Eldenroot** [comment]
Where to report then?

**Comment by TojikCZ** [comment]
Okay, I will post the link explicitly: https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/2878
This mention link leads to the new issue reported under the right repo.
![image](https://user-images.githubusercontent.com/5272796/210532514-3443a558-0fa6-432f-8f16-b2ccac559324.png)
