### ISSUE TITLE
Color change remaining time

### ISSUE THREAD

**Issue by yasars** [prusa3d/Prusa-Link#617]
Hi my friend can you add in Prusa Link and Prusa Connect ...color change remaining time? I have no informtion on the webinterface ... Can see only on lcd of prusa xx:xxC .... Thanks

**Comment by TojikCZ** [comment]
We already read it, so it shouldn't be that big of a deal to add the readout. Thank you for the suggestion

**Comment by yasars** [comment]
wow a miracle in the new prusalink it was added...
