### ISSUE TITLE
Possible wrong "Printer" label

### ISSUE THREAD

**Issue by mmoraes80** [prusa3d/Prusa-Link#655]
Hello,

After installing PrusaLink 0.7.0RC2, I noticed that the gray "Printer" label at the top of the page is currently showing the printer location instead of the printer's name.

Is this intentional or is it a minor code bug?

**Comment by tomashusakk** [comment]
![Screenshot 2023-02-13 at 14 29 43](https://user-images.githubusercontent.com/108595413/218471015-0554f804-9e56-43cd-9cc7-6891349b589b.png)
![Screenshot 2023-02-13 at 14 29 54](https://user-images.githubusercontent.com/108595413/218471017-b199e233-d57e-4026-bde1-d5eaa4db6281.png)

Hello,

Do you mean this printer label? There's a combined name of the printer and the location, as shown in the settings in the second screenshot.

**Comment by mmoraes80** [comment]
Yes!. apparently it was a glitch with my browser. When I refreshed the page, it fixed itself.
