### ISSUE TITLE
Microsoft® LifeCam HD-3000 not working with Prusa Link 0.7.0 RC 3

### ISSUE THREAD

**Issue by kchmiele** [prusa3d/Prusa-Link#712]
I'm using latest Prusa Link (0.7.0 rc 3) with the Logitech C170 webcam, which is working great. Unfortunately it's a very old webcam and the image quality isn't great. I connected a Microsoft LifeCam HD-3000 webcam which I used earlier with Octoprint and lo and behold, it does not get detected by Prusa Link at all.
I tried connecting it alongside the Logitech webcam and as the only webcam. Still nothing.

Using fswebcam to take a picture with the MS webcam as input device works just fine.

Prusa Link is installed on Raspberry Pi 3, the webcam's details are below:
```
chris@PrusaLinkMK3:~ $ v4l2-ctl --list-devices | grep cam

Webcam C170: Webcam C170 (usb-3f980000.usb-1.1.2):
	/dev/video0
	/dev/video1
	/dev/media3

Microsoft® LifeCam HD-3000: Mi (usb-3f980000.usb-1.2):
	/dev/video2
	/dev/video3
	/dev/media4

chris@PrusaLinkMK3:~ $ lsusb | grep cam
Bus 001 Device 007: ID 045e:0779 Microsoft Corp. LifeCam HD-3000
Bus 001 Device 006: ID 046d:082b Logitech, Inc. Webcam C170
```
This webcam is supported by the v4l2 driver.
Could you please look into it?

**Comment by TojikCZ** [comment]
Hi, could you send the syslog that can be found in the local web interface under settings? There might be a message that tells me why it didn't get connected even tho v4l2 detected it.

For example, I do not support any other formats than YUYV and MJPEG. It could be that it offers a different format. Also, it could just be erroring out for god knows what reason.

If nothing works, I'll try to get my hands on one and test.

**Comment by kchmiele** [comment]
Here's what happened when I plugged in the camera (from syslog):

Mar 28 16:54:28 PrusaLinkMK3 prusa.link.serial.serial_adapter[583]: WARNING: Error when connecting to serial according to user config:  auto {_renew_serial_connection():267}
Mar 28 16:54:28 PrusaLinkMK3 prusa.link.web.lib.classes[583]: INFO: 192.168.1.158 - "GET /api/job HTTP/1.1" 200 418 {log_message():45}
Mar 28 16:54:28 PrusaLinkMK3 prusa.link.web.lib.classes[583]: INFO: 192.168.1.158 - "GET /api/printer HTTP/1.1" 200 651 {log_message():45}
Mar 28 16:54:28 PrusaLinkMK3 prusa.link.web.lib.classes[583]: INFO: 192.168.1.158 - "GET /api/v1/cameras HTTP/1.1" 200 19 {log_message():45}
**_Mar 28 16:54:28 PrusaLinkMK3 kernel: [  520.401942] usb 1-1.1.3: new high-speed USB device number 6 using dwc_otg
Mar 28 16:54:28 PrusaLinkMK3 kernel: [  520.557994] usb 1-1.1.3: New USB device found, idVendor=045e, idProduct=0779, bcdDevice= 1.06
Mar 28 16:54:28 PrusaLinkMK3 kernel: [  520.558034] usb 1-1.1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=0
Mar 28 16:54:28 PrusaLinkMK3 kernel: [  520.558054] usb 1-1.1.3: Product: Microsoft® LifeCam HD-3000
Mar 28 16:54:28 PrusaLinkMK3 kernel: [  520.558072] usb 1-1.1.3: Manufacturer: Microsoft
Mar 28 16:54:28 PrusaLinkMK3 kernel: [  520.564181] usb 1-1.1.3: Found UVC 1.00 device Microsoft® LifeCam HD-3000 (045e:0779)
Mar 28 16:54:28 PrusaLinkMK3 kernel: [  520.571233] input: Microsoft® LifeCam HD-3000: Mi as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.1/1-1.1.3/1-1.1.3:1.0/input/input2
Mar 28 16:54:29 PrusaLinkMK3 mtp-probe: checking bus 1, device 6: "/sys/devices/platform/soc/3f980000.usb/usb1/1-1/1-1.1/1-1.1.3"
Mar 28 16:54:29 PrusaLinkMK3 mtp-probe: bus: 1, device: 6 was not an MTP device
Mar 28 16:54:29 PrusaLinkMK3 systemd-udevd[2846]: controlC2: Process '/usr/sbin/alsactl -E HOME=/run/alsa -E XDG_RUNTIME_DIR=/run/alsa/runtime restore 2' failed with exit code 99._**
Mar 28 16:54:29 PrusaLinkMK3 prusa.link.web.lib.classes[583]: INFO: 192.168.1.158 - "GET /api/printer HTTP/1.1" 200 651 {log_message():45}
Mar 28 16:54:29 PrusaLinkMK3 prusa.link.web.lib.classes[583]: INFO: 192.168.1.158 - "GET /api/job HTTP/1.1" 200 418 {log_message():45}
Mar 28 16:54:29 PrusaLinkMK3 prusa.link.web.lib.classes[583]: INFO: 192.168.1.158 - "GET /api/v1/cameras HTTP/1.1" 200 19 {log_message():45}
Mar 28 16:54:29 PrusaLinkMK3 systemd-udevd[2845]: event1: Process '/usr/sbin/th-cmd --socket /var/run/thd.socket --passfd --udev' failed with exit code 1.
Mar 28 16:54:29 PrusaLinkMK3 mtp-probe: checking bus 1, device 6: "/sys/devices/platform/soc/3f980000.usb/usb1/1-1/1-1.1/1-1.1.3"
Mar 28 16:54:29 PrusaLinkMK3 mtp-probe: bus: 1, device: 6 was not an MTP device

**Comment by TojikCZ** [comment]
Mine looks like this, is there any camera related output from PrusaLink? It does a scanning routine every 30s
```
2023-03-28 17:24:03,576 DEBUG {camera_governor._govern():31} [camera_governance]: Running the camera governance routine 
2023-03-28 17:24:03,581 INFO {v4l2_driver._scan():419} [camera_governance]: Camera id is Integrated_Webcam_HD: Integrate  
2023-03-28 17:24:03,585 INFO {v4l2_driver._scan():419} [camera_governance]: Camera id is Integrated_Webcam_HD: Integrate 
```

**Comment by kchmiele** [comment]
Found this in the log:

```
Mar 28 18:54:43 PrusaLinkMK3 prusa.link.web[1163]: INFO: Starting server for http://0.0.0.0:8080 {run_http():59}
Mar 28 18:54:43 PrusaLinkMK3 prusa.link.printer_adapter.prusa_link[1163]: INFO: Starting adapter for port auto {__init__():90}
Mar 28 18:54:43 PrusaLinkMK3 prusa.link.web[1163]: INFO: Authentication was set {init():38}
Mar 28 18:54:43 PrusaLinkMK3 prusa.link.web[1163]: INFO: No Api-Key was set. {init():46}
Mar 28 18:54:43 PrusaLinkMK3 prusa.link.web.lib.classes[1163]: INFO: 127.0.0.1 - "HEAD / HTTP/1.1" 200 0 {log_message():45}
Mar 28 18:54:43 PrusaLinkMK3 prusa.link.web.lib.classes[1163]: INFO: 127.0.0.1 - "HEAD / HTTP/1.1" 200 0 {log_message():45}
Mar 28 18:54:43 PrusaLinkMK3 prusa.link.cameras.v4l2_driver[1163]: INFO: Camera id is Microsoft® LifeCam HD-3000: Mi  {_scan():419}
Mar 28 18:54:43 PrusaLinkMK3 prusa.link.cameras.v4l2_driver[1163]: INFO: Camera id is Microsoft® LifeCam HD-3000: Mi  {_scan():419}
Mar 28 18:54:43 PrusaLinkMK3 prusa.link.printer_adapter.prusa_link[1163]: ERROR: Adapter was not start {run():72}#012Traceback (most recent call last):#012  File "/home/chris/.local/lib/python3.9/site-packages/prusa/link/daemon.py", line 70, in run#012    self.prusa_link = PrusaLink(self.cfg, self.settings)#012  File "/home/chris/.local/lib/python3.9/site-packages/prusa/link/printer_adapter/prusa_link.py", line 120, in __init__#012    self.camera_configurator = CameraConfigurator(#012  File "/home/chris/.local/lib/python3.9/site-packages/prusa/connect/printer/camera_configurator.py", line 53, in __init__#012    self.load_cameras(load_configs=True)#012  File "/home/chris/.local/lib/python3.9/site-packages/prusa/connect/printer/camera_configurator.py", line 98, in load_cameras#012    detected_configs = self._get_detected_cameras()#012  File "/home/chris/.local/lib/python3.9/site-packages/prusa/connect/printer/camera_configurator.py", line 205, in _get_detected_cameras#012    scanned.update(driver.scan())#012  File "/home/chris/.local/lib/python3.9/site-packages/prusa/connect/printer/camera_driver.py", line 116, in scan#012    camera_id = CameraDriver.make_hash(plaintext_id)#012  File "/home/chris/.local/lib/python3.9/site-packages/prusa/connect/printer/camera_driver.py", line 100, in make_hash#012    hashed_id = hashlib.blake2b(plaintext_id.encode("ascii"),#012UnicodeEncodeError: 'ascii' codec can't encode character '\xae' in position 9: ordinal not in range(128)
Mar 28 18:54:43 PrusaLinkMK3 prusa.link.web[1163]: INFO: Shutdown http {run_http():74}
Mar 28 18:54:43 PrusaLinkMK3 prusa.link.__main__[1163]: INFO: Shutdown {main():254}
```

**Comment by TojikCZ** [comment]
An ® symbol. Never knew device names could have characters >= 0x80. Also, forgot that decode("ascii") refuses to deal with those. Thanks for the report
