### ISSUE TITLE
Feature request: Upload directly to SD Card

### ISSUE THREAD

**Issue by Lukas-Heiligenbrunner** [prusa3d/Prusa-Link#715]
Hey, 
it would be a great enhancement to be able to upload a gcode-file directly to the printers sd card from prusa-connect via the uart. 
(Then one can easily upload a file to the printer, go there clean the bed, start print from sd, ...)

thanks a lot for your great software, keep up the good work!
kind regards.

**Comment by ondratu** [comment]
I understand very well, but answer is no. You can use mobile with PrusaConnect or PrusaLink, which is little bit faster, that browser.

**Comment by Lukas-Heiligenbrunner** [comment]
Thanks for clarification.
