### ISSUE TITLE
Display of folder name consistency match case 

### ISSUE THREAD

**Issue by theronarmandm** [prusa3d/Prusa-Link#723]
One can create the same folder name with different case settings.
For Example :
PrusaParts vs PRUSAPARTS

I understand that linux OS manages case sensitivity in this regards.
However when entering the folder the navigation link at the top sets the folder name always in upper case, thus indicating one is in the upper case folder even if one went into (as per the name example above) into the Camel cased folder.

So to replicate  :
1. In prusa slicer upload file to PRUSAPARTS/test.gcode
2. In prusa slicer upload file to PrusaParts/test2.gcode
3. Now navigate to Prusa Link
4. In Prusa Link there will be 2 folders PRUSAPARTS and PrusaParts
5. Each folder will contain the correct uploaded file as per step 1 and 2 (so this is correct)
6. When navigating to the folder created in step 2, PrusaParts the folder name at the top will show all upper case as PRUSAPARTS, which then is confusing , although its in the correct folder as per step 2. This can confuse a user as this can make one think that you are in the folder as per step 1 PRUSAPARTS.

**Comment by ondratu** [comment]
Yes, you are right, that is bug. Thanks for your report!
