### ISSUE TITLE
Use HTTPS instead of HTTP

### ISSUE THREAD

**Issue by shravan2x** [prusa3d/Prusa-Link#769]
Could an option be added to run the PrusaLink server over HTTPS? It would make HTTP authentication more secure

**Comment by ondratu** [comment]
That would be really great, but problem with local TLS certificates is, that there will be self-signed, or very difficult to manage. So at this moment, we use HTTP Digest, which is easiest way to implement on all platforms we use, with basic security options.

Another (best) way is stop using local web interface - which can be disable in future, and use only Connect. All our printers communicate with Connect over TLS or over encrypted way.

**Comment by shravan2x** [comment]
My concern with using Connect is create a dependence on a cloud server to use my own product. This creates concerns like:

1. Privacy of models being printed
2. Protection against Prusa cloud servers being shut down in the future
3. Protection against internet provider downtime

Even using a self-signed certificate is good as the connection data is encrypted. You could support both the HTTP and HTTPS ports, which is what HP OfficeJet printers do

**Comment by shravan2x** [comment]
@ondratu could you please consider my response above?
