### ISSUE TITLE
Add Support for MK4

### ISSUE THREAD

**Issue by mikedmor** [prusa3d/Prusa-Link#806]
In its current state, the MK4 is unable to do the following things with the built in PrusaLink:

- Control the printer
- Add/Manage Webcams
- Adjust Settings

I was going to spin up another Raspberry Pi I have laying around to utilize instead of the built in PrusaLink interface, but it does not currently appear that the MK4 is supported as I cannot get past the configuration Wizard page since it is not detected. Adding support for the MK4 would provide those missing features that the built-in PrusaLink is currently lacking. If these features are missing on the MK4 due to performance reason, an external device makes sense in order to add additional features.

**Comment by TojikCZ** [comment]
We'll see. I probably won't get assinged time to work on this. As it's implemented right now, adding support for another firmware that behaves a lot different would not be easy at all, and investing money into an alternative to our own product looks weird.

**Comment by florianbaer** [comment]
Seems that these features are now implemented. 
MK4 has a USB-C Port, can I connect a webcam to it and connect it with Prusa-Connect?
