### ISSUE TITLE
Feature Request: preheat printer

### ISSUE THREAD

**Issue by Jonas12354** [prusa3d/Prusa-Link#830]
How cool would it be if you could preheat your printer from within Prusa Link. Currently I am doing this on the printer itself before preparing my gcode. Would be great if this could be done all from the computer. What do you think?

**Comment by TojikCZ** [comment]
I opened a new issue in the proper place prusa3d/Prusa-Firmware-Buddy#3203

**Comment by TojikCZ** [comment]
Sorry, the xBuddy platform. I used the correct term in the new issue.
