### ISSUE TITLE
Wrinting to printer SD

### ISSUE THREAD

**Issue by sourekv** [prusa3d/Prusa-Link#844]
Hello,
what could I do to fix / enable wrinting to printer SD (pi card works)?

![image](https://github.com/prusa3d/Prusa-Link/assets/48099959/53970bab-1a62-4df9-ac96-480c257c0b77)

**Comment by sourekv** [comment]
![image](https://github.com/prusa3d/Prusa-Link/assets/48099959/bb8f309b-69d8-4b94-8a90-13f46b4ffe5c)

**Comment by TojikCZ** [comment]
It is not feasible to use gcodes to write to the printer's SD card. Sorry

**Comment by sourekv** [comment]
Then the app probably shouldn't look like it can :-(

**Comment by TojikCZ** [comment]
will check if we read the read only flag correctly in the link web ui

**Comment by sourekv** [comment]
![image](https://github.com/prusa3d/Prusa-Link/assets/48099959/be278675-508a-45cd-bb2f-60f5a9decfa2)
In this context make these icons for SD card very little sense.

**Comment by TojikCZ** [comment]
Soo just to clarify. What version of PrusaLink do you have?

The PrusaLink Gcodes tab is for files on the raspi sd card. The SD Card tab is for the files on the printer SD card. There should not be an option to upload there visible in the recent versions, if there is, please give us more details
