### ISSUE TITLE
Forum button is not correct

### ISSUE THREAD

**Issue by Krosta8** [prusa3d/Prusa-Link#851]
I know, that it is only very minor issue, but maybe good to address that.
In Prusa Connect (https://connect.prusa3d.com/), if I click "Forum" button, it is trying to **open https://forum.prusaprinters.org/forum/prusa-connect-prusalink/**
**instead of https://forum.prusa3d.com/forum/prusa-connect-prusalink/**

**Comment by TojikCZ** [comment]
Fixed in an upcoming release. Thanks for the report tho :)
