### ISSUE TITLE
Focus mode for Pi Camera 3

### ISSUE THREAD

**Issue by ingbrzy** [prusa3d/Prusa-Link#861]
Please add ability to adjust auto-focus feature (set focus mode manually) on Pi Camera 3 module... 

Unfortunately in default auto-focus is enabled but it is still out of focus (or focused on wrong area) due to print head fast moving..

Thank you

Useful documentation:
https://www.raspberrypi.com/documentation/computers/camera_software.html

https://github.com/Gordon999/Pi_LIbCamera_GUI

**Comment by ingbrzy** [comment]
This is how it looks now on 0.7.1RC1..
![snapshot-Camera-1697192405](https://github.com/prusa3d/Prusa-Link/assets/1762519/43fcfa9c-35ea-4f7c-a2ae-b594f9e2e260)

**Comment by TojikCZ** [comment]
Sorry for the clunky focusing procedure, but i am happy to see it working
