### ISSUE TITLE
API version

### ISSUE THREAD

**Issue by rforro** [prusa3d/Prusa-Link#884]
https://github.com/prusa3d/Prusa-Link/blob/ee1a1c3fe4cb333d6d4f786f8b35d6ed769834da/prusa/link/web/main.py#L245

Shouldn't be this set to `'api': "2.0.0",` version? The same version as Buddy FW is reporting, which supports the same V1 endpoints?

**Comment by TojikCZ** [comment]
Yup, seems about right. Thanks.
#892 will fix it
