### ISSUE TITLE
Printing Time not accurate ~23 hours into a 36 hour print

### ISSUE THREAD

**Issue by Braddg** [prusa3d/Prusa-Link#919]
Prusa XL 5T Printing Time not accurate.  It has been running for 23 hours at this point, but says "Less than a minute" under Printing Time.  I'm connected directly to the Prusa XL from my PC on a local network.  The Last Modified, Remaining time and Estimated end time all appear as expected. Prusa XL firmware 5.1.2

![Screenshot 2023-12-21 222128](https://github.com/prusa3d/Prusa-Link/assets/51935601/4d8c75b0-4ff4-4e08-a1aa-27feea076f7f)

**Comment by Braddg** [comment]
Just realized this should go under Prusa Link Web instead.  Closing

**Comment by TojikCZ** [comment]
Hi, it's probably prusa firmware buddy, i would move it, I just am in a holiday lazy mode today so I forgot
