### ISSUE TITLE
FEATURE REQUEST: Firmware version 

### ISSUE THREAD

**Issue by eWuPi** [prusa3d/Prusa-Link#949]
Please add information via PrusaLink about the version of the Firmware installed in the printer.
A useful function when writing, e.g. Issue, where I do not have direct access to the printer.

**Comment by Lowentwickler** [comment]
@eWuPi what printer model are we talking about?

**Comment by eWuPi** [comment]
MK4
MK4_MK3.9_firmware_5.1.3

**Comment by 3d-gussner** [comment]
@eWuPi This is the repository for the external SBC/computer PrusaLink. For the MINI, MK3.5, MK3.9, MK4 and XL PrusaLink is running on the controller board. Please open MK4 related issues [here](https://github.com/prusa3d/Prusa-Firmware-Buddy)

Please close this issue here.

**Comment by 3d-gussner** [comment]
@Prusa-Support Please close this issue
