### ISSUE TITLE
Prusalink status isnt updating from previous state to "ready"

### ISSUE THREAD

**Issue by Zero-Circle** [prusa3d/Prusa-Link#972]
When the printer is marked in prusa connect or from the menu as "ready" Prusa link doesnt reset the status of the printer to ready, it instead stays in the previous state it was in prior to being marked as "ready".

![image](https://github.com/prusa3d/Prusa-Link/assets/111734887/c0c09e23-55af-488b-b42d-c06199599df9)
![image](https://github.com/prusa3d/Prusa-Link/assets/111734887/34d5aad7-0060-4795-a7b0-82d66cba0ad3)

The above two screenshots are taken after the printer has been marked as ready.

**Comment by 3d-gussner** [comment]
@Zero-Circle This repository is for the MK3/S/+ and MK2.5/S PrusaLink on SBC (like Raspberry Pi) please close the issue here and reopen it in https://github.com/prusa3d/Prusa-Firmware-Buddy
PrusaLink on the MINI, MK3.5, MK3.9, MK4 and XL are implemented on the controller board.

**Comment by Zero-Circle** [comment]
Marked closed as this is the wrong location for this issue. Moved to this [topic here.](https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/4058)
