### ISSUE TITLE
Problem with checking updates

### ISSUE THREAD

**Issue by slajsik** [prusa3d/Prusa-Link#985]
I have the current Prusa Link version (0.8.1) and the current firmware version (3.14.0).
![problem_check_update](https://github.com/user-attachments/assets/b9909fac-b3aa-4098-8419-237694ebd0de)

**Comment by ondratu** [comment]
You have last version. This is not bug.

**Comment by slajsik** [comment]
In Prusa link 0.7.2 "You have the latest version" was displayed after installation.  Now showing red banner, I assumed no update server available.  Thank you for the explanation.
