### ISSUE TITLE
[Feature Request] consider adding support for MQTT

### ISSUE THREAD

**Issue by mgx0** [prusa3d/Prusa-Link#994]
Hi there, 

please consider adding support for sending MQTT messages. Such messages could contain:
- printer state
- printing status (including a picture snapshot URL)

it could be then possible to integrate into home automation system (node-red). I can imagine being notified of printing status/printer state by a way of my choice (Pushover, Telegram).

or is there a REST API to query the Prusa-link for these information already? could not find anything about it. My goal is the Prusa-link to work off the internet (offline) only connected to my home network.

thanks

**Comment by 3d-gussner** [comment]
@mgx0 Please have a look at https://www.home-assistant.io/integrations/prusalink/ and https://github.com/home-assistant/core/tree/dev/homeassistant/components/prusalink here you may find some ideas how to integrate PrusaLink to  your home automation system.

**Comment by mgx0** [comment]
Wonderful, thanks!
